### ISSUE TITLE
ordering the components

### ISSUE THREAD

**Issue by mikeshams** [jamesmchacko/Capstone-Project_G2#1]
what points did you consider when choosing a company to order your components from?

**Comment by jamesmchacko** [comment]
When ordering the component I took note of few things they are

- Availability
- Review of the product from  other users
- Estimated Shipping Time and Date
- Cost of the product
- Quality of the product

Among these points, I gave most priority to Shipping time and product review. we cannot have any delay on the component delivery.

**Comment by mikeshams** [comment]
customer service?

**Comment by ChristyRachel** [comment]
Yes, Customer service is also important, since if we need to do return or refund we really need their support.

**Comment by jamesmchacko** [comment]
We have ordered most of the components from Amazon which have 30 days return policy. The product ordered from Walmart also has a return policy and both these companies have very good customer service. We can call them and enquire about the product. The company from which I ordered ESP32 and Max30102 are good electronics supply companies. They have sent us the components through DHL  and have good customer service.
