### ISSUE TITLE
Power Management

### ISSUE THREAD

**Issue by mikeshams** [jamesmchacko/Capstone-Project_G2#11]
1. In terms of software, what can we do to ensure the ESP32 goes into sleep mode whenever there is no input signal?
2. Revise your ppt file accordingly!
3. Demonstrate it!

**Comment by Premil12** [comment]
I have updated the ppt and ready for demonstration.
[EMBT-ESE 4009.pptx](https://github.com/jamesmchacko/Capstone-Project_G2/files/6928634/EMBT-ESE.4009.pptx)

**Comment by mikeshams** [comment]
Will those components off whose Vcc pins are connected to the ESP32 whenever ESP32 goes into sleep mode?

**Comment by Premil12** [comment]
Yes, In this sleep mode, everything is switched off including CPU, Wi-Fi, Bluetooth, Peripherals, etc. Only the ULP coprocessor, RTC and RTC Memory are turned on in this mode.. Hence all components connected to the ESP32 will be turned off. As all the data is stored in the RTC memory and the RTC memory is active on sleep mode we can still retain all the previous data.

**Comment by mikeshams** [comment]
Do you think that would be a good idea to enforce the ESP32 to go into the sleep mode for a while or we need to find another viable solution for power management?

**Comment by Premil12** [comment]
we can turn off the Bluetooth module without going into deep-sleep mode,like this way we can save power and also we preferred using components which have some inbuilt power saving methods like our DS18B20 temperature sensor which can draw power from data line as well as external power supplies.  The part of the code of the code we  used to turn off the Bluetooth is given below.

void disableBluetooth(){
  btStop();     /// stopping our bluetooth module 
}
void setModemSleep(){        // calling the function
  disableBluetooth();
  setCpuFrequencyMhz(80);       //setting the cpu frequency to 80 Mhz
}
[Untitled presentation.pptx](https://github.com/jamesmchacko/Capstone-Project_G2/files/6963178/Untitled.presentation.pptx)

**Comment by Premil12** [comment]
updated ppt file.
[EMBT-ESE 4009 (1).pptx](https://github.com/jamesmchacko/Capstone-Project_G2/files/6971124/EMBT-ESE.4009.1.pptx)
