### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by mikeshams** [jamesmchacko/Capstone-Project_G2#2]
add a description to your project for the depository

**Comment by jamesmchacko** [comment]
Sir, I have added the description for our project. You can see the Read.MD file now

**Comment by mikeshams** [comment]
Revise it asap!

**Comment by ChristyRachel** [comment]
We updated the readme.md sir.
In the description, we added Proteus, KiCAD and EasyEDA in the software requirements

**Comment by jamesmchacko** [comment]
we edited the software requirement part in our description.
