### ISSUE TITLE
Remaining components/ tools

### ISSUE THREAD

**Issue by mikeshams** [jamesmchacko/Capstone-Project_G2#3]
Show me the rest of your components/ tools as soon as you receive them:
ESP32
Max30100 Pulse Oximetry sensor 
Heart rate sensor 
Rechargeable Li-ion  Battery
GSM Module
GPS Module
DMM

**Comment by jamesmchacko** [comment]
yes, sir, I will add a photo of the components as soon as I get it.

**Comment by mikeshams** [comment]
use camera for them!

**Comment by ChristyRachel** [comment]
Sure sir

**Comment by mikeshams** [comment]
Show me the rest of your components/ tools as soon as you receive them:
Max30102 Pulse Oximetry sensor & Heart rate sensor
GPS Module

**Comment by jamesmchacko** [comment]
I got the max30102 sensor and I am still waiting for the GPS module. I will get the GPS module by today or tomorrow and I can show all the components together next session.
Thank you

**Comment by mikeshams** [comment]
I updated the milestone.

**Comment by jamesmchacko** [comment]
Sir, I received both the max30102 and GPS module which I can show it today during the class
Thank you
