### ISSUE TITLE
Testing Components

### ISSUE THREAD

**Issue by mikeshams** [jamesmchacko/Capstone-Project_G2#4]
Demonstrate the remaining components when receive:
ESP32
Max30100 Pulse Oximetry sensor 
Heart rate sensor 
GSM Module
GPS Module

**Comment by ChristyRachel** [comment]
Hi Sir, ESP 32 is ready to do testing

**Comment by mikeshams** [comment]
Please test 
GSM Module
GPS Module

**Comment by ChristyRachel** [comment]
GSM Module is ready to test

**Comment by ChristyRachel** [comment]
Hi Prof., Premil Prasannan already shown our GSM Module is working well as a part of his presentation.

**Comment by ChristyRachel** [comment]
We not yet received the GPS Module

**Comment by ChristyRachel** [comment]
Hi Prof., we received the Neo-6M GPS module, but we are not getting the proper output. So it would be great if we get little more time to work on it. Thank you

**Comment by mikeshams** [comment]
noted.
