### ISSUE TITLE
ESP 32 SET UP

### ISSUE THREAD

**Issue by mikeshams** [jamesmchacko/Capstone-Project_G2#5]
Add the code and pictures of the connection with the LED... to your powerpoint

**Comment by fahd7796** [comment]
[PPT3 ESP32 Interface .pptx](https://github.com/jamesmchacko/Capstone-Project_G2/files/6665112/PPT3.ESP32.Interface.pptx)
 Here is the PPT3. Esp32 Microcontroller interface with code and pictures as required 
 thank you
