### ISSUE TITLE
EKG sensor interfacing

### ISSUE THREAD

**Issue by mikeshams** [jamesmchacko/Capstone-Project_G2#7]
Modify your references based on APA style!

**Comment by Premil12** [comment]
Changed my references based on APA format
[interfacing of EKG (2).pptx](https://github.com/jamesmchacko/Capstone-Project_G2/files/6779753/interfacing.of.EKG.2.pptx)

**Comment by Premil12** [comment]
sorry sir, i updated my references on APA format
[interfacing of EKG (3).pptx](https://github.com/jamesmchacko/Capstone-Project_G2/files/6786220/interfacing.of.EKG.3.pptx)
