### ISSUE TITLE
Push Button Interfacing

### ISSUE THREAD

**Issue by mikeshams** [jamesmchacko/Capstone-Project_G2#8]
Demonstrate the task!

**Comment by ChristyRachel** [comment]
Sorry sir, still we are not getting the output. Please give us more time. Thank you

**Comment by ChristyRachel** [comment]
Hi sir, we got the output. 
You  can find it at this link: 
https://github.com/jamesmchacko/Capstone-Project_G2/blob/main/PushButtonOutput.mp4

**Comment by ChristyRachel** [comment]
Sorry sir, I accidently closed it

**Comment by mikeshams** [comment]
What was the root cause making you not be able to demonstrate the task before?

**Comment by ChristyRachel** [comment]
Because of extreme weather conditions, we were not getting exact data from the GPS module. So we bought an extension antenna, and by placing it outside the apartment, it was able to get the location data from the GPS module.
