### ISSUE TITLE
Real Time Operation 

### ISSUE THREAD

**Issue by mikeshams** [jamesmchacko/Capstone-Project_G2#9]
1. Implement Real Time Operation! 
Tip: In the main code, all devices can be initialized as the threads and queues. For each interfacing, you have already created individual tasks and are all initialized in main function. In the main code, function is created to initialize the main thread and create a queue of main thread. This thread will act as a mediator and helps synchronizing different threads .  Each new thread is created and each thread created has its ID to be stored at referred location. You can assign different priorities to the threads. In this way you are executing different tasks in parallel. 
2. Reflect your method and the details on your ppt file!

**Comment by jamesmchacko** [comment]
1.For the real-time operation there were three tasks. Temperature sensor, EKG, and Spo2.I was able to multitask temperature and EKG with stable output. Right now I am working to get stable output for SPO2

**Comment by jamesmchacko** [comment]
Sir,
I was able to multi-task the sensor output and can demonstrate it in the next session.

**Comment by jamesmchacko** [comment]
Sir I have made necessary changes in the presentation file 
Thank You


[component  testing (3).pptx](https://github.com/jamesmchacko/Capstone-Project_G2/files/6903346/component.testing.3.pptx)
